### ISSUE TITLE
can I upload it to solar2d free plugin directory?

### ISSUE THREAD

**Issue by Shchvova** [kayahanbaskeser/hms-ads-kit-integration-into-corona-project#1]
Hey!
First of all thanks a lot for making this and [that](https://medium.com/huawei-developers/hms-ads-kit-integration-into-solar2d-corona-project-a1b3fcaf8b09)
I'm Vlad, leading developer of Solar2D. I was wondering if I can add your plugin into Solar2D directory.
Also, you miss license on your code. I usually I put MIT licese on everything, otherwise it may be dangerous to use your code.
Also, you don't have to use Solar2D native. You can only build plugin in Native, then use it in Simulator. Anyway. Humble requesst to allow me to add it as a plugin and please add license so I can do it safely.

**Comment by kayahanbaskeser** [comment]
Hi,
Of course, you can add this plugin to Solar2D directory.
And after you said, I added the MIT license.
And I will try the plugin in Native. 
Thanks 👍

**Comment by Shchvova** [comment]
Done. I [forked](https://github.com/solar2d/com.solar2d-plugin.huaweiads) your repo, added "documentation" into readme and added to [S2D directory](https://plugins.solar2d.com/?search=huawei). If you want, I can make a pull request.
Now it just works from build.settings.

**Comment by kayahanbaskeser** [comment]
Thank you, please make a pull request. And also i will create new plugins for some HMS kits.
